//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Northwind.Dal.SqlScripts.OrderRepository.SqlServer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Queries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Queries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Northwind.Dal.SqlScripts.OrderRepository.SqlServer.Queries", typeof(Queries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [dbo].[Orders] 
        ///       ([OrderDate], [RequiredDate], [ShippedDate], [ShipName], [ShipAddress], [ShipCity], [ShipRegion], [ShipPostalCode], [ShipCountry])  
        ///VALUES (@OrderDate, @RequiredDate, @ShippedDate, @ShipName, @ShipAddress, @ShipCity, @ShipRegion, @ShipPostalCode, @ShipCountry);
        ///
        ///SELECT [OrderID]
        ///      ,[OrderDate]
        ///      ,[RequiredDate]
        ///      ,[ShippedDate]
        ///      ,[ShipName]
        ///      ,[ShipAddress]
        ///      ,[ShipCity]
        ///      ,[ShipRegion]
        ///      ,[ShipPostalCode]
        ///      ,[ShipCountry] [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddOrder {
            get {
                return ResourceManager.GetString("AddOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [dbo].[Orders] 
        ///SET [ShippedDate] = @ShippedDate
        ///WHERE [OrderID] = @Id;
        ///.
        /// </summary>
        internal static string CloseOrder {
            get {
                return ResourceManager.GetString("CloseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM [dbo].[Orders]
        ///WHERE [OrderID] = @Id
        ///.
        /// </summary>
        internal static string DeleteOrder {
            get {
                return ResourceManager.GetString("DeleteOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [OrderID]
        ///      ,[OrderDate]
        ///      ,[RequiredDate]
        ///      ,[ShippedDate]
        ///      ,[ShipName]
        ///      ,[ShipAddress]
        ///      ,[ShipCity]
        ///      ,[ShipRegion]
        ///      ,[ShipPostalCode]
        ///      ,[ShipCountry]
        ///  FROM [dbo].[Orders]
        ///  WHERE [OrderID] = @id;
        ///
        ///SELECT [Details].[UnitPrice]
        ///      ,[Details].[Quantity]
        ///      ,[Details].[Discount]
        ///	  ,[Products].[ProductID]
        ///      ,[Products].[ProductName]
        ///      ,[Products].[QuantityPerUnit]
        ///      ,[Products].[UnitPrice]
        ///      ,[Products].[UnitsInStock]        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetDetailedInfo {
            get {
                return ResourceManager.GetString("GetDetailedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [OrderID]
        ///      ,[OrderDate]
        ///      ,[RequiredDate]
        ///      ,[ShippedDate]
        ///      ,[ShipName]
        ///      ,[ShipAddress]
        ///      ,[ShipCity]
        ///      ,[ShipRegion]
        ///      ,[ShipPostalCode]
        ///      ,[ShipCountry]
        ///  FROM [dbo].[Orders];
        ///.
        /// </summary>
        internal static string GetOrders {
            get {
                return ResourceManager.GetString("GetOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [dbo].[Orders] 
        ///SET [OrderDate] = @OrderDate
        ///WHERE [OrderID] = @Id;
        ///.
        /// </summary>
        internal static string StartProgress {
            get {
                return ResourceManager.GetString("StartProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [dbo].[Orders] 
        ///SET [RequiredDate] = @RequiredDate, 
        ///    [ShipName] = @ShipName,
        ///    [ShipAddress] = @ShipAddress,
        ///    [ShipCity] = @ShipCity,
        ///    [ShipRegion] = @ShipRegion,
        ///    [ShipPostalCode] = @ShipPostalCode,
        ///    [ShipCountry] = @ShipCountry
        ///WHERE
        ///    [OrderID] = @Id;
        ///
        ///SELECT [OrderID]
        ///      ,[OrderDate]
        ///      ,[RequiredDate]
        ///      ,[ShippedDate]
        ///      ,[ShipName]
        ///      ,[ShipAddress]
        ///      ,[ShipCity]
        ///      ,[ShipRegion]
        ///      ,[ShipPostalCode]
        ///      ,[ShipCountry]
        ///  FROM  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpdateOrder {
            get {
                return ResourceManager.GetString("UpdateOrder", resourceCulture);
            }
        }
    }
}
